### ISSUE TITLE
Testando a linguagem Markdown

### ISSUE THREAD

**Issue by antoniocesar7** [antoniocesar7/aprendendonode1#13]
Vamos testar esta linguagem

**Comment by antoniocesar7** [comment]
# Título nível 1
---
## Título nível 2
---
###Título nível 3
---
####Título nível 4
---
#####Título nível 5
---
######Título nível 6
---
Estou ~aprendendo~ linguagem __*Markdown*__ no **sábado** de reposição de __carnaval__ no dia 22/02/2023

####Listas:
1. Teste
2. Teste
2.1 teste
2.2 teste


####LIsta Demarcada
* Teste
* Teste
   * tteste
###Lista de Tarefas
- [ ] Criar página principal
- [ ] Criar página de cadastro
- [x] Criar página de consulta

##Imagens

   
          

 
![ Colando imagens ](https://user-images.githubusercontent.com/79478380/221366096-3fc408f2-7944-49e1-9bce-4929f8d2767d.png)
[acessar](https://www.google.com.br/)

**Comment by antoniocesar7** [comment]
###Tabelas
Num | Nome | Nota
---|---|---
1|Antonio César|10
2|AsdrubalCésar|10
3|Fulan César|09
4|Ciclano César|08
5|Beltrano César|07
6|Joaquim César|05

**Comment by antoniocesar7** [comment]
Comentando com a linguagem `Markdonw-monoespaçado-fundo-cinza`
### Trechos de programas###
```
num = int(input('teste'))
if num-=ttt;
   print('Qualquer coisa...')
else

```

**Comment by antoniocesar7** [comment]
##Colocando emoji
inserindo 👍 💯 🔢 🥇:grinning:
[emojis](https://github.com/ikatyang)

**Comment by antoniocesar7** [comment]
> ##Colocando emoji inserindo 👍 💯 🔢 🥇😀 [emojis](https://github.com/ikatyang)

**Comment by lucascalu** [comment]
> Vamos testar esta linguagem

Ok vamos testar!

**Comment by antoniocesar7** [comment]
> > Vamos testar esta linguagem
> 
> Ok vamos testar!

Show! TMJ!
